### ISSUE TITLE
As a human, i do a lot of typos. We should add tests to prevent them and other errors.

### ISSUE THREAD

**Issue by renatodeleao** [whitesmith/qnorr-styles#20]
For functions and mixins.

- https://github.com/oddbird/true#usage
- Articles:
  - https://seesparkbox.com/foundry/how_and_why_we_unit_test_our_sass
  - https://itnext.io/setting-up-sass-unit-testing-in-your-project-b683a2e8ac03
- Example on how [to setup with jest](https://github.com/diego-codes/sass-testing-template)

**Comment by tomasmcm** [comment]
🤚
